/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PrimeButton: typeof import('primevue/button')['default']
    PrimeCard: typeof import('primevue/card')['default']
    PrimeColumn: typeof import('primevue/column')['default']
    PrimeDataTable: typeof import('primevue/datatable')['default']
    PrimeDatePicker: typeof import('primevue/datepicker')['default']
    PrimeDialog: typeof import('primevue/dialog')['default']
    PrimeFloatLabel: typeof import('primevue/floatlabel')['default']
    PrimeIconField: typeof import('primevue/iconfield')['default']
    PrimeInputGroup: typeof import('primevue/inputgroup')['default']
    PrimeInputIcon: typeof import('primevue/inputicon')['default']
    PrimeInputMask: typeof import('primevue/inputmask')['default']
    PrimeInputNumber: typeof import('primevue/inputnumber')['default']
    PrimeInputText: typeof import('primevue/inputtext')['default']
    PrimeMenubar: typeof import('primevue/menubar')['default']
    PrimeMessage: typeof import('primevue/message')['default']
    PrimeSelect: typeof import('primevue/select')['default']
    PrimeTag: typeof import('primevue/tag')['default']
    PrimeToast: typeof import('primevue/toast')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
